[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
gas_reports = ["*"]
remappings  = [
    "forge-std=lib/forge-std/src",
    "openzeppelin=lib/openzeppelin-contracts/contracts",
]
# Konfigurasi untuk RPC Endpoints
[rpc_endpoints]
sepolia = "${BASE_SEPOLIA_RPC_URL}"

# Konfigurasi untuk verifikasi Etherscan
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
base-sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/api", chain = 84532 }