[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
gas_reports = ["*"]
remappings  = [
    "forge-std=lib/forge-std/src",
    "openzeppelin=lib/openzeppelin-contracts/contracts",
]
[rpc_endpoints]
linea = "${LINEA_RPC_URL}"
linea-sepolia = "${RPC_URL}"

[etherscan]
linea = { key = "${LINEASCAN_API_KEY}" }
linea-sepolia = { key = "${LINEASCAN_API_KEY}" }